// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mirama.Modules.PM.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mirama.Modules.PM.Migrations
{
    [DbContext(typeof(PMDbContext))]
    [Migration("20260904142612_RemoveIdempotencyRecords")]
    partial class RemoveIdempotencyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Member.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsInherited")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "MemberId")
                        .IsUnique();

                    b.ToTable("ProjectMember", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Milestone.ProjectMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMilestone", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Project", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Team.ProjectTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ProjectId", "TeamId")
                        .IsUnique();

                    b.ToTable("ProjectTeam", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.CycleTemplate.CycleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTemplateId");

                    b.ToTable("CycleTemplate", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.MilestoneTemplate.MilestoneTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DayOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTemplateId");

                    b.ToTable("MilestoneTemplate", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ProjectTemplate", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.TaskTemplate.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTemplateTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentTemplateTaskId");

                    b.HasIndex("ProjectTemplateId");

                    b.ToTable("TaskTemplate", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.Priority.PriorityConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WorkflowConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowConfigIdForTaskPriority")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowConfigId");

                    b.HasIndex("WorkflowConfigIdForTaskPriority");

                    b.ToTable("PriorityConfig", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.Status.StatusConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkflowConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowConfigIdForTaskStatus")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowConfigId");

                    b.HasIndex("WorkflowConfigIdForTaskStatus");

                    b.ToTable("StatusConfig", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("WorkflowConfig", "projects");
                });

            modelBuilder.Entity("Mirama.SharedKernel.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "projects");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Member.ProjectMember", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.Project.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Milestone.ProjectMilestone", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.Project.Project", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Team.ProjectTeam", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.Project.Project", null)
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.CycleTemplate.CycleTemplate", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.ProjectTemplate", null)
                        .WithMany("CycleTemplates")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.MilestoneTemplate.MilestoneTemplate", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.ProjectTemplate", null)
                        .WithMany("MilestoneTemplates")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.TaskTemplate.TaskTemplate", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.TaskTemplate.TaskTemplate", null)
                        .WithMany()
                        .HasForeignKey("ParentTemplateTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.ProjectTemplate", null)
                        .WithMany("TaskTemplates")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.Priority.PriorityConfig", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", null)
                        .WithMany("Priorities")
                        .HasForeignKey("WorkflowConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", null)
                        .WithMany("TaskPriorities")
                        .HasForeignKey("WorkflowConfigIdForTaskPriority")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.Status.StatusConfig", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", null)
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowConfigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", null)
                        .WithMany("TaskStatuses")
                        .HasForeignKey("WorkflowConfigIdForTaskStatus")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", b =>
                {
                    b.HasOne("Mirama.Modules.PM.Domain.Aggregates.Project.Project", null)
                        .WithOne()
                        .HasForeignKey("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.Project.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Milestones");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.ProjectTemplate.ProjectTemplate", b =>
                {
                    b.Navigation("CycleTemplates");

                    b.Navigation("MilestoneTemplates");

                    b.Navigation("TaskTemplates");
                });

            modelBuilder.Entity("Mirama.Modules.PM.Domain.Aggregates.WorkflowConfig.WorkflowConfig", b =>
                {
                    b.Navigation("Priorities");

                    b.Navigation("Statuses");

                    b.Navigation("TaskPriorities");

                    b.Navigation("TaskStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
