// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mirama.Modules.Clients.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mirama.Modules.Clients.Migrations
{
    [DbContext(typeof(ClientsDbContext))]
    [Migration("20260904155119_AddIntakeFormDomain")]
    partial class AddIntakeFormDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clients")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ActivityLog.ClientActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoggedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientActivityLogEntry", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LeadSource")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Clients", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ClientPortalInvitation.ClientPortalInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PortalInvitations", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ClientPortalUser.ClientPortalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "ContactId")
                        .IsUnique();

                    b.ToTable("PortalUsers", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.Contact.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Email")
                        .IsUnique();

                    b.ToTable("Contacts", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.PipelineHistory.PipelineStageHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PipelineStageHistoryEntry", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Contract.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartyType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PartyType", "PartyId");

                    b.ToTable("Contract", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Contract.ContractTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractTerm", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("IntakeForm", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.IntakeFormSubmission.IntakeFormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvertedToClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("IntakeFormId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntakeFormVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Responses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IntakeFormId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("IntakeFormSubmission", "clients");
                });

            modelBuilder.Entity("Mirama.SharedKernel.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "clients");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ActivityLog.ClientActivityLogEntry", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", null)
                        .WithMany("ActivityLog")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ClientPortalInvitation.ClientPortalInvitation", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", null)
                        .WithMany("PortalInvitations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.ClientPortalUser.ClientPortalUser", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", null)
                        .WithMany("PortalUsers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.Contact.Contact", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.PipelineHistory.PipelineStageHistoryEntry", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", null)
                        .WithMany("PipelineHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Contract.ContractTerm", b =>
                {
                    b.HasOne("Mirama.Modules.Clients.Domain.Aggregates.Contract.Contract", null)
                        .WithMany("Terms")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeForm", b =>
                {
                    b.OwnsMany("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeFormField", "Fields", b1 =>
                        {
                            b1.Property<Guid>("IntakeFormId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsRequired");

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Options");

                            b1.Property<string>("SectionKey");

                            b1.Property<int>("Type");

                            b1.HasKey("IntakeFormId", "__synthesizedOrdinal");

                            b1.ToTable("IntakeForm", "clients");

                            b1.ToJson("Fields");

                            b1.WithOwner()
                                .HasForeignKey("IntakeFormId");

                            b1.OwnsOne("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeFieldCondition", "VisibleWhen", b2 =>
                                {
                                    b2.Property<Guid>("IntakeFormFieldIntakeFormId");

                                    b2.Property<int>("IntakeFormField__synthesizedOrdinal");

                                    b2.Property<string>("DependsOnFieldKey")
                                        .IsRequired();

                                    b2.Property<int>("Operator");

                                    b2.Property<string>("Value");

                                    b2.HasKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");

                                    b2.ToTable("IntakeForm", "clients");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeFieldValidationRule", "Validation", b2 =>
                                {
                                    b2.Property<Guid>("IntakeFormFieldIntakeFormId");

                                    b2.Property<int>("IntakeFormField__synthesizedOrdinal");

                                    b2.Property<DateTime?>("MaxDate");

                                    b2.Property<int?>("MaxLength");

                                    b2.Property<int?>("MaxSelections");

                                    b2.Property<decimal?>("MaxValue");

                                    b2.Property<DateTime?>("MinDate");

                                    b2.Property<int?>("MinLength");

                                    b2.Property<int?>("MinSelections");

                                    b2.Property<decimal?>("MinValue");

                                    b2.Property<string>("Pattern");

                                    b2.HasKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");

                                    b2.ToTable("IntakeForm", "clients");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeFormFieldPresentation", "Presentation", b2 =>
                                {
                                    b2.Property<Guid>("IntakeFormFieldIntakeFormId");

                                    b2.Property<int>("IntakeFormField__synthesizedOrdinal");

                                    b2.Property<string>("HelpText");

                                    b2.Property<string>("Placeholder");

                                    b2.Property<int>("Width");

                                    b2.HasKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");

                                    b2.ToTable("IntakeForm", "clients");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeFormFieldIntakeFormId", "IntakeFormField__synthesizedOrdinal");
                                });

                            b1.Navigation("Presentation")
                                .IsRequired();

                            b1.Navigation("Validation");

                            b1.Navigation("VisibleWhen");
                        });

                    b.OwnsMany("Mirama.Modules.Clients.Domain.Aggregates.IntakeForm.IntakeFormSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("IntakeFormId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description");

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("IntakeFormId", "__synthesizedOrdinal");

                            b1.ToTable("IntakeForm", "clients");

                            b1.ToJson("Sections");

                            b1.WithOwner()
                                .HasForeignKey("IntakeFormId");
                        });

                    b.Navigation("Fields");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Client.Client", b =>
                {
                    b.Navigation("ActivityLog");

                    b.Navigation("Contacts");

                    b.Navigation("PipelineHistory");

                    b.Navigation("PortalInvitations");

                    b.Navigation("PortalUsers");
                });

            modelBuilder.Entity("Mirama.Modules.Clients.Domain.Aggregates.Contract.Contract", b =>
                {
                    b.Navigation("Terms");
                });
#pragma warning restore 612, 618
        }
    }
}
